[project]
name = "atividade1-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.0.3",
    "jupyterlab>=4.2.5",
    "numpy>=2.1.2",
    "scikit-learn>=1.5.2",
]
